import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import { createElement } from "react";

const PETROL = "#07312C";
const TEAL   = "#0E9E92";

const styles = StyleSheet.create({
  page:       { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#111" },
  header:     { marginBottom: 24 },
  title:      { fontSize: 18, fontWeight: "bold", color: PETROL, marginBottom: 4 },
  subtitle:   { fontSize: 10, color: "#666" },
  divider:    { borderBottomWidth: 1, borderBottomColor: "#E5E7EB", marginVertical: 12 },
  row:        { marginBottom: 16, padding: 12, backgroundColor: "#F5F8F7", borderRadius: 4 },
  label:      { fontSize: 8, color: TEAL, fontWeight: "bold", textTransform: "uppercase", marginBottom: 2 },
  value:      { fontSize: 10, color: "#111", marginBottom: 6 },
  pill:       { fontSize: 8, padding: "2 6", borderRadius: 10, alignSelf: "flex-start" },
  pillOpen:   { backgroundColor: "#FEF3C7", color: "#92400E" },
  pillDone:   { backgroundColor: "#D1FAE5", color: "#065F46" },
  meta:       { fontSize: 8, color: "#6B7280", marginTop: 4 },
  footer:     { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9CA3AF" },
});

type Request = {
  id: string;
  category: string;
  description: string;
  logged_at: string;
  acknowledged_at: string | null;
  resolved_at: string | null;
  landlord_notes: string | null;
};

function fmt(iso: string | null) {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-ZA", { day: "numeric", month: "short", year: "numeric" });
}

function RequestRow({ r }: { r: Request }) {
  const resolved = !!r.resolved_at;
  return createElement(View, { style: styles.row },
    createElement(Text, { style: styles.label }, r.category.toUpperCase()),
    createElement(Text, { style: styles.value }, r.description),
    createElement(View, { style: [styles.pill, resolved ? styles.pillDone : styles.pillOpen] },
      createElement(Text, null, resolved ? "Resolved" : "Open"),
    ),
    createElement(Text, { style: styles.meta },
      `Logged: ${fmt(r.logged_at)}  |  Acknowledged: ${fmt(r.acknowledged_at)}  |  Resolved: ${fmt(r.resolved_at)}`,
    ),
    r.landlord_notes
      ? createElement(Text, { style: { ...styles.meta, marginTop: 4, fontStyle: "italic" } },
          `Landlord notes: ${r.landlord_notes}`,
        )
      : null,
  );
}

export async function buildMaintenancePdf(
  requests: Request[],
  tenantName: string,
  propertyAddress: string,
): Promise<Buffer> {
  const doc = createElement(
    Document,
    null,
    createElement(
      Page,
      { size: "A4", style: styles.page },
      // header
      createElement(View, { style: styles.header },
        createElement(Text, { style: styles.title }, "Maintenance Log"),
        createElement(Text, { style: styles.subtitle }, `Tenant: ${tenantName}`),
        createElement(Text, { style: styles.subtitle }, `Property: ${propertyAddress}`),
        createElement(Text, { style: styles.subtitle }, `Exported: ${fmt(new Date().toISOString())}`),
      ),
      createElement(View, { style: styles.divider }),
      // rows
      ...requests.map((r) => createElement(RequestRow, { key: r.id, r })),
      // footer
      createElement(
        Text,
        { style: styles.footer },
        "Generated by RentalRep · rentalrep.co.za",
      ),
    ),
  );

  return renderToBuffer(doc) as Promise<Buffer>;
}
